spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
#      data-locations: classpath:populateDB.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist
security:
  jwt:
    secret: dXpma2xVVUpVSktramZsd2pra3NkZmhrc2pkZG5rempzZGZqamtsc2Jka2RidmR2YnpkZ3hkZmJ4aHNkZ2RmYmhzZmJzZGdzZGZic2mI=
    access: 3600000
    refresh: 2592000000
springdoc:
  override-with-generic-response: false




